# /netlify.toml
[build]
  publish = "."

# ---------- Redirects ----------
[[redirects]]
  from = "/diensten"
  to = "/diensten/"
  status = 301
  force = true

# ---------- Global security headers ----------
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), camera=(), microphone=(), interest-cohort=()"
    # Minimalistische CSP – pas domeinen aan indien je extra scripts/fonts laadt
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; script-src 'self' 'unsafe-inline' plausible.io; connect-src 'self' plausible.io; frame-ancestors 'self'; base-uri 'self'; form-action 'self'"

# ---------- Long-cache voor static assets ----------
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ---------- Kort-cache voor HTML ----------
[[headers]]
  for = "/*"
  [headers.values]
    # Netlify matched hier ook HTML; overschrijft de asset-routes niet
    Cache-Control = "public, max-age=300, must-revalidate"
