# /netlify.toml
[build]
  publish = "."

# -------------------------------------------------
# Redirects (pas aan naar jouw canonieke domein)
# -------------------------------------------------
# 👉 Forceer 'www' (vervang naar wens naar non-www)
[[redirects]]
  from = "https://buscemigroup.be/*"
  to = "https://www.buscemigroup.be/:splat"
  status = 301
  force = true

# Trailing slash voor directory routes (bv. /diensten)
[[redirects]]
  from = "/diensten"
  to = "/diensten/"
  status = 301
  force = true

# -------------------------------------------------
# Global Security Headers
# -------------------------------------------------
[[headers]]
  for = "/*"
  [headers.values]
    # Transport & TLS
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

    # Framing & MIME sniffing & referrers
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Browser features
    Permissions-Policy = "geolocation=(), camera=(), microphone=(), interest-cohort=()"

    # XSS (legacy; moderne browsers gebruiken CSP)
    X-XSS-Protection = "0"

    # Content Security Policy
    # - 'unsafe-inline' is nodig zolang je inline <script> en style-attributen gebruikt.
    # - Voeg hier extra domeinen toe als je later bv. Calendly embedt.
    Content-Security-Policy = """
      default-src 'self';
      base-uri 'self';
      frame-ancestors 'self';
      object-src 'none';
      upgrade-insecure-requests;
      img-src 'self' data: https:;
      font-src 'self' data: https://fonts.gstatic.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      script-src 'self' 'unsafe-inline' https://plausible.io;
      connect-src 'self' https://plausible.io;
      form-action 'self'
    """

# -------------------------------------------------
# Caching
# -------------------------------------------------
# Lange cache voor statische assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Korte cache voor HTML (mag vaker verversen)
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"

# (Optioneel) iets langere cache voor sitemap/robots
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"
