# netlify.toml — security headers + caching

# (Optioneel) als je een build stap hebt, pas 'publish' aan.
[build]
  publish = "."

# Algemene security headers
[[headers]]
  for = "/*"
  [headers.values]
  Strict-Transport-Security      = "max-age=63072000; includeSubDomains; preload"
  Referrer-Policy               = "strict-origin-when-cross-origin"
  X-Content-Type-Options        = "nosniff"
  X-Frame-Options               = "DENY"
  X-XSS-Protection              = "0"
  Permissions-Policy            = "geolocation=(), microphone=(), camera=(), interest-cohort=()"
  Cross-Origin-Opener-Policy    = "same-origin"
  Cross-Origin-Resource-Policy  = "same-origin"
  X-DNS-Prefetch-Control        = "off"

# Strikte CSP — werkt met jouw huidige setup (geen externe scripts)
# Als je later externe bronnen toevoegt (fonts/analytics), moeten die hier worden toegestaan.
[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    base-uri 'self';
    script-src 'self';
    style-src 'self' 'unsafe-inline';
    img-src 'self' data: blob:;
    font-src 'self';
    connect-src 'self';
    form-action 'self' https://*.netlify.app https://*.netlify.com;
    frame-ancestors 'none';
    upgrade-insecure-requests;
  """

# Lange cache voor statische assets (pas het pad aan als jij /assets of /static gebruikt)
[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Service worker zelf nooit keihard cachen
[[headers]]
  for = "/sw.js"
  [headers.values]
  Cache-Control = "no-cache"
